package com.enuygun.casestudy.model.enuygun

import com.google.gson.annotations.SerializedName


data class Currencies (

  @SerializedName("AED" ) var AED : String? = null,
  @SerializedName("ARS" ) var ARS : String? = null,
  @SerializedName("AUD" ) var AUD : String? = null,
  @SerializedName("AZN" ) var AZN : String? = null,
  @SerializedName("BDT" ) var BDT : String? = null,
  @SerializedName("BHD" ) var BHD : String? = null,
  @SerializedName("BOB" ) var BOB : String? = null,
  @SerializedName("BRL" ) var BRL : String? = null,
  @SerializedName("BYN" ) var BYN : String? = null,
  @SerializedName("CAD" ) var CAD : String? = null,
  @SerializedName("CHF" ) var CHF : String? = null,
  @SerializedName("CLP" ) var CLP : String? = null,
  @SerializedName("CNY" ) var CNY : String? = null,
  @SerializedName("COP" ) var COP : String? = null,
  @SerializedName("CRC" ) var CRC : String? = null,
  @SerializedName("DKK" ) var DKK : String? = null,
  @SerializedName("DZD" ) var DZD : String? = null,
  @SerializedName("EGP" ) var EGP : String? = null,
  @SerializedName("EUR" ) var EUR : String? = null,
  @SerializedName("GBP" ) var GBP : String? = null,
  @SerializedName("HKD" ) var HKD : String? = null,
  @SerializedName("ILS" ) var ILS : String? = null,
  @SerializedName("INR" ) var INR : String? = null,
  @SerializedName("IQD" ) var IQD : String? = null,
  @SerializedName("JOD" ) var JOD : String? = null,
  @SerializedName("JPY" ) var JPY : String? = null,
  @SerializedName("KGS" ) var KGS : String? = null,
  @SerializedName("KRW" ) var KRW : String? = null,
  @SerializedName("KWD" ) var KWD : String? = null,
  @SerializedName("KZT" ) var KZT : String? = null,
  @SerializedName("LBP" ) var LBP : String? = null,
  @SerializedName("LKR" ) var LKR : String? = null,
  @SerializedName("MAD" ) var MAD : String? = null,
  @SerializedName("MXN" ) var MXN : String? = null,
  @SerializedName("MYR" ) var MYR : String? = null,
  @SerializedName("NOK" ) var NOK : String? = null,
  @SerializedName("NZD" ) var NZD : String? = null,
  @SerializedName("OMR" ) var OMR : String? = null,
  @SerializedName("PAB" ) var PAB : String? = null,
  @SerializedName("PEN" ) var PEN : String? = null,
  @SerializedName("PHP" ) var PHP : String? = null,
  @SerializedName("PKR" ) var PKR : String? = null,
  @SerializedName("QAR" ) var QAR : String? = null,
  @SerializedName("RUB" ) var RUB : String? = null,
  @SerializedName("SAR" ) var SAR : String? = null,
  @SerializedName("SEK" ) var SEK : String? = null,
  @SerializedName("SGD" ) var SGD : String? = null,
  @SerializedName("THB" ) var THB : String? = null,
  @SerializedName("TND" ) var TND : String? = null,
  @SerializedName("TRY" ) var TRY : String? = null,
  @SerializedName("TWD" ) var TWD : String? = null,
  @SerializedName("USD" ) var USD : String? = null,
  @SerializedName("ENC" ) var ENC : Int?    = null

)